#!/bin/bash
declare -a arr=("asia-east1-b" "europe-west1-b" "us-east1-b" "us-central1-b")

for cluster in "${arr[@]}"; do
  echo ""
  echo "${cluster}"
  kubectl --context=${cluster} get secrets 
done
